---
title: "W201 Portfolio"
author: "Steve Yang"
date: "MIDS Fall 2017"
site: bookdown::bookdown_site
documentclass: book
---

<!-- This won't be displayed but it will initialize your R session. Add any R libraries you need here. -->
```{r init,include=FALSE,echo=FALSE}
library(magrittr)
```


# Welcome! {-}

This site contains my portfolio of projects from "Research Design and Applications for Data and Analysis" as part of the UC Berkeley MIDS program. Currently, this involves some conceptual data science problems, with more updates to come that include implementation.

### Abstract of Quantifying NFL Player Production via Machine "Watching Film" {-}

Finding talent in the NFL plays a crucial role in building a successful team. Scouting is both a high stakes job and one which could have long term consequences on a team's well-being. The predominant ways that NFL scouts look for new players to sign include "watching film" and looking at player statistics, both of which fall short. The first allows for detailed analyses of players, but since they are subject to the opinion of individuals, it is difficult to reconcile measures of player productivity across the league. The latter allows for measures that can be agreed upon across the league, but fails to examine all the important and necessary details.

In this proposal, I explore ways in which we could use data that have been made recently available for a comprehensive approach to measuring player productivity -- ultimately leading to better decisions when signing players to a team. The methodology involves measuring player statistics, similar to those that are already measured, then to use machine learning algorithms that analyze real-time sensor data to attribute those statistics among all involved parties.

### Abstract of Predicting the Next Hit Song {-}

Major record labels alone invest around $4.5 billion anually on artists. Being able to predict the likelihood of a hit song by a given artist is an important first step to determining if that artist will be a smart investment for the label. 

## About the author {-}

After receiving my BA in Economics and a minor in Music Technology from USC, I wanted to discover a career that could join the two fields. First I worked as an analyst in litigation and economic consulting, followed by my position at a marketing analytics company as a Data Engineer. Both positions helped me discover my love for data science, but I continued to maintain a strong interest in the music and entertainment industry. Now, I am in my first year of my Masters in Information and Data Science degree at UC Berkeley to learn and apply data science techniques to solve problems in the entertainment and media industry.

*Updated: `r Sys.Date()`*
